### PR TITLE
Update install manual and test

### PR DESCRIPTION
**Pull request by darkrain-nl**

### CODE REVIEW

**Comment by darkrain-nl** [comment]
Why close this without merging?

**Comment by JohnvandeVrugt** [comment]
Changes are committed to trunk, right?
When I log in to GitHub I see your latest changes...

**Comment by darkrain-nl** [comment]
I don't see those changes in the current master.
The last ones fix a part in the INSTALL-PI and INSTALL_WIN is previously forgot.

So can you please consider reopening and merging?

**Comment by JohnvandeVrugt** [comment]
I apologise for being mistaken this release being #26.
I now DID merge this into the master branch and will prepare a new release.

**Comment by darkrain-nl** [comment]
No problem, all good now!

**Pull request merged**
