### PR TITLE
Prevent unnecessary burner state updates

### PR DESCRIPTION
**Pull request by arjanwaard**

### CODE REVIEW

**Comment by JohnvandeVrugt** [comment]
Hi Arjan, 

your commit seems to be valid, however, I'm currenty working on a complete rework of the plugin.
In that code, if I'm not mistaken,  each device checks its own previous value before updating domoticz.
I expect to release this rework in the coming days...

**Comment by arjanwaard** [comment]
No problem, but be aware the burner state has 3 on states and only 1 off
state. Thanks for doing the work on the plugin by the way, much appreciated
!

**Comment by darkrain-nl** [comment]
> 
> 
> Hi Arjan,
> 
> your commit seems to be valid, however, I'm currenty working on a complete rework of the plugin.
> In that code, if I'm not mistaken, each device checks its own previous value before updating domoticz.
> I expect to release this rework in the coming days...

Hi @JohnvandeVrugt ,

If you need someone to test the rewritten code other then yourself, just let me know.
Or just create a beta branch or something like that.

I'm happy to help and don't mind to do some bugfixing (as far as I can, still not a Python guru).

**Comment by arjanwaard** [comment]
Closed waiting for the refactoring

**Pull request closed without merging**
